### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by martgnz** [bcnfs/bcnfs.github.io#13]
What do you think about HTTPS support?

It can be done with [Cloudflare](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare) if we don't want to move away from GitHub Pages but we would have to manage the DNS from there.

**Comment by aleixpol** [comment]
Ugh, yes. We need https. I'll send victor and @tsdgeos and we see what they suggest.

**Comment by martgnz** [comment]
Should be done now.
