### ISSUE TITLE
Members counter is broken

### ISSUE THREAD

**Issue by tsdgeos** [bcnfs/bcnfs.github.io#26]
I think it's because meetup has stopped supporting the API key and now oauth needs to be used.

@martgnz You did the original code, do you have any idea how using oauth2 would look like?

**Comment by martgnz** [comment]
Unfortunately I don't think we have a way to get the meetup list or member count anymore. Oauth2 would be rather annoying and require some sort of login screen and authorisation flow AFAIK.

Maybe we could do show the events by exporting the event list to some sort of Google calendar or similar.

I contacted meetup support to see if they can provide a solution. In the meantime I'll disable both features.

**Comment by martgnz** [comment]
Meetup replied and said there's no other way to do this now. I've been taking a look at their docs and implementing Oauth2 doesn't make sense (each visitor would get redirected to meetup.com and have to authorise our 'app', and then come back to the website, and the token would get stale after X hours).

For the calendar integration I can write something that renders the RSS feed from meetup but we would need to run a proxy like [cors-anywhere](https://github.com/Rob--W/cors-anywhere/) because of CORS (not sure if it's worth it).

**Comment by aleixpol** [comment]
> Meetup replied and said there's no other way to do this now. I've been taking a look at their docs and implementing Oauth2 doesn't make sense (each visitor would get redirected to meetup.com and have to authorise our 'app', and then come back to the website, and the token would get stale after X hours).

I'd say fuck it. The current plan is to be less of a meetup group and more of FOSS people who meet monthly. We don't need to define ourselves through the followers.

That said, are you sure it's broken? The error we get is lack of authorization, maybe the key we're using expired:
`{"errors":[{"code":"auth_fail","message":"Invalid signature"}]}`

> For the calendar integration I can write something that renders the RSS feed from meetup but we would need to run a proxy like [cors-anywhere](https://github.com/Rob--W/cors-anywhere/) because of CORS (not sure if it's worth it).

Here they seem to hint at feeds being available?
https://www.meetup.com/meetup_api/feeds/

**Comment by martgnz** [comment]
I don't think is possible, this page doesn't have a form to renew the key anymore https://secure.meetup.com/meetup_api/key/

Yeah, there are feeds (e.g. https://www.meetup.com/Barcelona-Free-Software/events/rss/), but we cannot fetch them from our site directly, we would need to request the file through a proxy fir that to work (e.g. https://cors-anywhere.herokuapp.com/https://www.meetup.com/Barcelona-Free-Software/events/rss/).

The feeds don't display past events either.

**Comment by tsdgeos** [comment]
meh :/
