### ISSUE TITLE
Subdomain Takeover

### ISSUE THREAD

**Issue by JoeMilian** [bcnfs/bcnfs.github.io#43]
Hey,

I noticed you had an unclaimed GitHub page, I took it over so no attacker is able to use it.

The subdomain: https://las2019.bcnfs.org/

Github suggests the following: "We strongly recommend not using wildcard DNS records, such as *.example.com. A wildcard DNS record will allow anyone to host a site at one of your subdomains."

I hope I have informed you enough, If there are any issues please don't hesitate to message me.

Kind regards,

Joe (https://twitter.com/JoeMilian1)

**Comment by tsdgeos** [comment]
Hi Joe, 

thanks for the heads up!

We think we have fixed the configuration so that this can not happen anymore, but we would be very happy if you can have a second look just in case :)

Thanks again for the notifcation!
